### ISSUE TITLE
Can't use custom sphinx.cfg / problems reading the cfg file

### ISSUE THREAD

**Issue by rolfschr** [stef/zphinx-zerver#1]
Hi,

I managed to compile the oracle binary but I'm having issue running it. I have a sphinx.cfg which seems to cause issues:

```bash
$ cat sphinx.cfg
[server]
ssl_key = ./ssl_key.pem
ssl_cert = ./ssl_cert.pem

$ ../oracle
error loading config sphinx.cfg: error.invalid_value # <----- I guess this is not expected?
cfg.address: 127.0.0.1
cfg.port: 8080
cfg.datadir: /var/lib/sphinx
cfg.ssl_key: server.pem
cfg.ssl_cert: certs.pem
cfg.verbose: true
ERROR: could not open file 'server.pem' for reading
cast causes pointer to be null
[1]    240914 abort (core dumped)  ../oracle
```

I used https://github.com/aeronavery/zig-toml/commit/299e2d9f87816a5ce374853e03f13176b821b81e as input. I don't have experience with zig so I don't know how I can locate the issue more precisely.

**Comment by stef** [comment]
uh, yeah. this is a discrepancy between the python and the zig config file. apparently toml needs strings in double quotes. and hence it doesn't parse your cfg and uses the default value, which of course does not exist.

**Comment by rolfschr** [comment]
Hi, thanks for the quick reply and sorry for my late reaction. Double quotes fixed the issue.

**Comment by rolfschr** [comment]
FYI, it would be really cool if I could use the same `sphinx.cfg` file for zphinx as well as `pwdsphinx`. However, the former needs double quotes strings as you mentioned above and the latter doesn't work with double quotes. I was unable to use a working `sphinx.cfg` for both implementations. Either I get the error above, or - when strings are quoted - the Python impl throws:

```
# address (hostname) quoted
Traceback (most recent call last):                                                                                                                                                                                 
  File "/nix/store/p4g90v8pd6gwamwlaw190yw8fc7h7ck8-python3.8-pwdsphinx-f7acc8c/lib/python3.8/site-packages/pwdsphinx/oracle.py", line 358, in main                                                                
    s.bind((address, port))                                                                                                                                                                                        
socket.gaierror: [Errno -2] Name or service not known  

# ssl file paths quoted
Traceback (most recent call last):                                                                                                                                                                                 
  File "/nix/store/p4g90v8pd6gwamwlaw190yw8fc7h7ck8-python3.8-pwdsphinx-f7acc8c/bin/.oracle-wrapped", line 9, in <module>                                                                                          
    sys.exit(main())                                                                                                                                                                                               
  File "/nix/store/p4g90v8pd6gwamwlaw190yw8fc7h7ck8-python3.8-pwdsphinx-f7acc8c/lib/python3.8/site-packages/pwdsphinx/oracle.py", line 353, in main                                                                
    ctx.load_cert_chain(certfile=ssl_cert, keyfile=ssl_key)                                                                                                                                                        
FileNotFoundError: [Errno 2] No such file or directory 
```

**Comment by stef** [comment]
i think that is possible. i'll fix this in the python ref impl.
